source "https://rubygems.org"

gem "webrick"
gem "pygments.rb"
gem "asciidoctor"
gem "asciidoctor-diagram"
gem "jekyll"
gem "jekyll-feed"
gem "jekyll-asciidoc"
gem "jekyll-paginate"
gem "jekyll-watch"
gem "jekyll-plantuml"
gem "jekyll-seo-tag"
gem "minima"
